AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-cognito

  Sample SAM Template for sam-cognito

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
  
  SignUpApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.signUpHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Environment:
        Variables:
          REGION: us-east-2
          USER_POOL_ID: us-east-2_MhH1DMpMv
          CLIENT_ID: 4h2arnmqcu4lheck42qdgvv661
      Events:
        SignUp:
          Type: Api
          Properties:
            Path: /signup
            Method: post
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
    
  ConfirmUserApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.confirmUserHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Environment:
        Variables:
          REGION: us-east-2
          USER_POOL_ID: us-east-2_MhH1DMpMv
          CLIENT_ID: 4h2arnmqcu4lheck42qdgvv661
      Events:
        SignUp:
          Type: Api
          Properties:
            Path: /confirmuser
            Method: post
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
            
  SignInApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.signInHandler
      Runtime: nodejs18.x
      Environment:
        Variables:
          REGION: us-east-2
          USER_POOL_ID: us-east-2_MhH1DMpMv
          CLIENT_ID: 4h2arnmqcu4lheck42qdgvv661
      Events:
        SignUp:
          Type: Api
          Properties:
            Path: /signin
            Method: post
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
  
  HelloWorldWithAuth:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.authHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        HelloWorldWithAuth:
          Type: Api
          Properties:
            Path: /hellowithauth
            Method: get
            RestApiId: !Ref AppApi
            Auth:
              Authorizer: CognitoAuthorizer  #Adding authorizer to the end point
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
  
  AppApi: 
    DependsOn: UserPool
    Type: AWS::Serverless::Api
    Properties:
      Name: HelloWorldAPI
      StageName: api
      Cors: "'*'"
      Auth: #creating an authorizer to api
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:us-east-2:503694153160:userpool/us-east-2_MhH1DMpMv
  
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: MyUserPoolDemo
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false

  # ApplicationResourceGroup:
  #   Type: AWS::ResourceGroups::Group
  #   Properties:
  #     Name:
  #       Fn::Join:
  #       - ''
  #       - - ApplicationInsights-SAM-
  #         - Ref: AWS::StackName
  #     ResourceQuery:
  #       Type: CLOUDFORMATION_STACK_1_0
  # ApplicationInsightsMonitoring:
  #   Type: AWS::ApplicationInsights::Application
  #   Properties:
  #     ResourceGroupName:
  #       Fn::Join:
  #       - ''
  #       - - ApplicationInsights-SAM-
  #         - Ref: AWS::StackName
  #     AutoConfigurationEnabled: 'true'
  #   DependsOn: ApplicationResourceGroup
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
